### ISSUE TITLE
how can I get the Enqueue url

### ISSUE THREAD

**Issue by zhangz4** [docusign/connect-node-listener-aws#1]
in the project **connect-csharp-worker-aws** the **Enqueue url** is used, 
where can i get the **Enqueue url**

**Comment by LarryKlugerDS** [comment]
You mean the [QUEUE_URL](https://github.com/docusign/connect-node-listener-aws/blob/master/index.js#L175) setting?

That's the queue url from the Simple Queuing Service queue. See step 6 of the [installation instructions](https://github.com/docusign/connect-node-listener-aws/blob/master/docs/INSTALLATION_2_sqs_queue.md).

**Comment by zhangz4** [comment]
Thank you for your answer. 
I want to know the value in bold below of project [connect-csharp-worker-aws](https://github.com/docusign/connect-csharp-worker-aws#installing-the-lambda-listener) 
_Install the example Connect listener for AWS on AWS. At the end of this step, you will have the Queue URL, Queue Region and **Enqueue url** that you need for the next step._

**Comment by LarryKlugerDS** [comment]
The Enqueue url is the url of the Lambda listener. It is used in two places:

1. It is used in the DocuSign eSignature Administration tool to set up the Connect webhook connection.
1. It is used to **test** the AWS system. It is used as the `TEST_ENQUEUE_URL` setting in the worker's configuration file. [C# example](https://github.com/docusign/connect-csharp-worker-aws/blob/master/connect-csharp-worker-aws/App.config_example.txt#L29).

It is the **API endpoint** field in this screenshot:
![API Gateway panel](https://github.com/docusign/connect-node-listener-aws/blob/master/docs/aws.l.07.lambda_create.png?raw=true)

**Comment by LarryKlugerDS** [comment]
The Queue URL, and Enqueue url are the same thing. I will fix the docs.

**Comment by zhangz4** [comment]
Thank you very very much.

**Comment by LarryKlugerDS** [comment]
Oops, I was wrong. Please see my updated comments, above.

**Comment by LarryKlugerDS** [comment]
The enqueue URL is used by the worker to test the listener. The worker sends a message to the listener as if the worker is the DocuSign Connect system.

I'm sorry for the confusion.

**Comment by zhangz4** [comment]
I got it.
thanks for your answer.
