### ISSUE TITLE
Typo in Authorization header

### ISSUE THREAD

**Issue by kennethteo** [docusign/connect-node-listener-aws#2]
Have recently used this sample to try out Docusign Connect. Am new to Connect but seems like there is a typo now with the Authorization header name. Perhaps has something to do with AWS API Gateway or recent changes to Connect (considering the date of this repo)

Original:
authRaw0 = (event.headers && event.headers.**Authorization**) || ''

Corrected and working as of 18 Oct:
authRaw0 = (event.headers && event.headers.**authorization**) || ''

**Comment by LarryKlugerDS** [comment]
Hi, Did you create your own API Gateway [Mapping Template](https://docs.aws.amazon.com/apigateway/latest/developerguide/rest-api-data-transformations.html)? Here's an [article on the subject](https://kennbrodhagen.net/2015/12/02/how-to-access-http-headers-using-aws-api-gateway-and-lambda/).

If you did use the default, then it sounds like there's been a change somewhere. 

But I'm concerned that in some circumstances it will still be `.Authorization` 
I will update the code.

**Comment by kennethteo** [comment]
> Hi, Did you create your own API Gateway [Mapping Template](https://docs.aws.amazon.com/apigateway/latest/developerguide/rest-api-data-transformations.html)? Here's an [article on the subject](https://kennbrodhagen.net/2015/12/02/how-to-access-http-headers-using-aws-api-gateway-and-lambda/).
> 
> If you did use the default, then it sounds like there's been a change somewhere.
> 
> But I'm concerned that in some circumstances it will still be `.Authorization`
> I will update the code.

Cool! Thanks for updating! 
Guess the difference for me was that I created the API Gateway from the Lambda creation wizard hence no way to define any models. But yeah your code adjustment will cover this exception 👍

**Comment by LarryKlugerDS** [comment]
Thanks for the update.

**Comment by LarryKlugerDS** [comment]
Please connect with me on Linked In: https://www.linkedin.com/in/larrykluger/ 
Thank you,
Larry
